# Applications and general CLI tools; runtime versions belong to mise.
# Unmanaged: Hermes, Appium, Deno, idb-companion, CuaDriver, HHKB and Raycast.
# Never use brew bundle cleanup with this file.
tap "coderabbitai/tap"
tap "tuist/tuist"

# Shell and everyday CLI tools
brew "mise"
brew "curl"
brew "wget"
brew "git"
brew "ripgrep"
brew "fd"
brew "bat"
brew "eza"
brew "fzf"
brew "zoxide"
brew "git-delta"
brew "tree"
brew "jq"
brew "yq"
brew "htop"
brew "btop"
brew "gh"
brew "lazygit"
brew "direnv"
brew "tlrc"
brew "starship"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "mas"
brew "m-cli"

# Editor, language servers and formatters (Dart comes with Flutter)
brew "neovim"
brew "tree-sitter-cli"
brew "lua-language-server"
brew "rust-analyzer"
brew "typescript-language-server"
brew "vscode-langservers-extracted"
brew "stylua"
brew "nixfmt"
brew "shellcheck"
brew "prettier"

# Development, AI and media tools discovered on this Mac
brew "agent-browser"
brew "block-goose-cli"
brew "cmake"
brew "cargo-about"
brew "cargo-edit"
brew "cargo-expand"
brew "cocoapods"
brew "coderabbitai/tap/git-gtr"
brew "ffmpeg"
brew "dprint"
brew "firebase-cli"
brew "googleworkspace-cli"
brew "grpc"
brew "librsvg"
brew "ollama"
brew "opencode"
brew "protobuf"
brew "sox"
brew "swift-format"
brew "swift-protobuf"
brew "swiftformat"
brew "swiftlint"
brew "tuist/tuist/tuist@4.155.3"
brew "uv"
brew "xcodegen"
brew "yt-dlp"

# Desktop and CLI applications distributed as casks.
cask "1password-cli"
cask "android-studio"
cask "chatgpt"
cask "claude-code"
cask "codex"
cask "cursor"
cask "cursor-cli"
cask "docker-desktop"
cask "gcloud-cli"
cask "google-chrome"
cask "icon-composer"
cask "slack"
cask "thebrowsercompany-dia"
cask "visual-studio-code"
cask "wezterm"

# Fonts previously installed by Home Manager.
cask "font-jetbrains-mono-nerd-font"
cask "font-fira-code-nerd-font"
cask "font-hack-nerd-font"
cask "font-meslo-lg-nerd-font"
