# Also initialize PATH in non-login interactive shells.
source "$HOME/.config/zsh/.zprofile"

autoload -Uz compinit
compinit
zstyle ':completion:*' menu select
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'

HISTFILE="$HOME/.local/share/zsh/history"
mkdir -p "${HISTFILE:h}"
HISTSIZE=10000
SAVEHIST=10000
setopt HIST_IGNORE_DUPS SHARE_HISTORY
bindkey "^[[A" history-search-backward
bindkey "^[[B" history-search-forward

eval "$(mise activate zsh --shims)"
eval "$(mise completion zsh)"
eval "$(direnv hook zsh)"
eval "$(starship init zsh)"
eval "$(zoxide init zsh --cmd cd)"

export FZF_DEFAULT_COMMAND='fd --type f --hidden --exclude .git'
export FZF_DEFAULT_OPTS='--height 40% --layout=reverse --border --inline-info'
export FZF_ALT_C_COMMAND='fd --type d --hidden --exclude .git'
export FZF_ALT_C_OPTS="--preview 'tree -C {} | head -200'"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_CTRL_T_OPTS="--preview 'bat --color=always --style=numbers --line-range=:500 {}'"
source <(fzf --zsh)

source /opt/homebrew/share/zsh-autosuggestions/zsh-autosuggestions.zsh
[[ -f "$HOME/.zshrc.local" ]] && source "$HOME/.zshrc.local"

function pd() {
  cd "$1" && mise current
}
function mise-reinstall() {
  mise uninstall "$1" && mise install "$1"
}

# Syntax highlighting should be loaded after other ZLE widgets.
source /opt/homebrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
